baseURL = 'http://example.org/'
languageCode = 'es'
title = 'El mini blog🤙'
theme = "paper"
[params.homeInfoParams]
Title = "Bienvenido a nuestro mini blog, disfruta de nuestros posts"
Content = "Puedes revisar nuestros proyectos en GitHub"
 [params.profileMode.buttons]
 name = "Github"
 url= "https://github.com/enchiladasdeml"